spring.application.name=demo

#server.port=${PORT:40324}
#spring.datasource.url=jdbc:postgresql://localhost:5432/blog
#spring.datasource.username=postgres
#spring.datasource.password=1234

server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

jwt.secret=ThisIsSecretSetByMePssdKranthi@123UserNameHero
#24 hours
jwt.expiration=86400000

#thymeleaf
spring.thymeleaf.cache=false


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# this shows the sql queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#postgresql://blog_db_1y9n_user:ZR0IieoqgH7M28Yjo4yJU1yu4Dbl5hZ0@dpg-d71c2ln5r7bs73dpo4t0-a/blog_db_1y9n
#blog_db_1y9n_user
#ZR0IieoqgH7M28Yjo4yJU1yu4Dbl5hZ0
